### ISSUE TITLE
Time Series charts shows all X-ticks

### ISSUE THREAD

**Issue by JonathanChavezTamales** [googleinterns/step180-2020#19]
Charts on mixed-content don't look properly formatted because it's rendering every x-tick.

**Comment by ernestognw** [comment]
Could you please add a screenshot? I found a problem with a .filter function that was running every render, but I don't really know if it is related.

**Comment by JonathanChavezTamales** [comment]
> Could you please add a screenshot? I found a problem with a .filter function that was running every render, but I don't really know if it is related.

Resolved in a meeting some days ago.

**Comment by JonathanChavezTamales** [comment]
Resolved in a pod meeting.
